# Node.js（Fastify） + React + PostgreSQL 用 docker-compose
services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./web/.env
    volumes:
      - ./web:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gacha_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
